version: "3"

services:
    mariadb:
        container_name: mariadb
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=laravel
            - MARIADB_DATABASE=laravel
            - MYSQL_PASSWORD=laravel
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ~/.docker-conf/mariadb/data:/var/lib/mysql
        networks:
            - app-network

    testdb:
        container_name: testdb
        image: mariadb
        ports:
            - "3307:3306"
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=test
            - MARIADB_DATABASE=test
            - MYSQL_PASSWORD=test
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ~/.docker-conf/testdb/data:/var/lib/mysql
        networks:
            - app-network

    adminer:
        image: adminer
        restart: always
        ports:
            - 7777:8080
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: config/php
        ports:
            - "8003:80"
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini`
        networks:
            - app-network

    webserver:
        image: nginx
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
